services:
  rutbis-api:
    container_name: rutbis-api
    image: neddy1298/rutbis-api:0.1.4
    ports:
      - "8080:8080"
    environment:
      DATABASE_USERNAME: rutbis
      DATABASE_PASSWORD: rutbis123
      DATABASE_URL: jdbc:postgresql://rutbis-api-postgres:5432/rutbis-api
  rutbis-api-postgres:
    container_name: rutbis-api-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: rutbis
      POSTGRES_PASSWORD: rutbis123
      POSTGRES_DB: rutbis-api
    ports:
      - "5432:5432"