### Create Terminal

POST http://localhost:8080/api/terminal
X-Api-Key: rutbis123
Content-Type: application/json
Accept: application/json

{
  "terminalId": "CGK",
  "terminalName": "Soekarno-Hatta International Airport",
  "terminalLocation": "Tangerang, Banten",
  "terminalImage": "https://example.com/images/soekarno-hatta.jpg",
  "serviceTime": "00:00 - 24:00"
}

### Create Bus

POST http://localhost:8080/api/bus
X-Api-Key: rutbis123
Content-Type: application/json
Accept: application/json

{
  "busId": "DAMRI001",
  "busLicense": "B 1234 DAM",
  "busName": "DAMRI",
  "busIcon": "https://example.com/images/damri-icon.png",
  "busImage": "https://example.com/images/damri-bus.jpg",
  "price": 50000
}

### Get All Terminals

GET http://localhost:8080/api/journeys
X-Api-Key: rutbis123
Accept: application/json
