name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login rutbisapi.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
      - name: Build and push Docker image
        run: |
          docker build -t rutbisapi.azurecr.io/rutbis-api:$(date +%s) .
          docker push rutbisapi.azurecr.io/rutbis-api:$(date +%s)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: rutbisapi
          images: rutbisapi.azurecr.io/rutbis-api:0.0.1
          slot-name: dev
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}

